In [660]:
import pandas as pd
import numpy as np

test, train = pd.read_csv('../test_no_class.csv'), pd.read_csv('../train.csv')
display(test.head()), display(train.head())

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,39,Male,2,2,1,2,2,2,1,2,2,2,2,0.70,?,48,4.4,?,1
1,41,Feamle,2,1,1,1,1,2,2,2,2,2,2,0.70,81,53,5.0,74,1
2,28,maled,1,2,1,1,1,2,1,2,2,2,2,1.60,44,123,4.0,46,1
3,36,maled,1,2,1,1,1,2,1,2,2,2,2,1.00,?,45,4.0,57,1
4,32,M,2,2,2,2,2,2,2,2,2,2,2,0.70,102,64,4.0,90,1

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,48,meale,1,2,1,1,2,2,1,2,1,1,1,4.80,123,157,2.7,31,2,DIE
1,51,Male,2,2,1,2,2,2,1,1,1,2,1,1.00,?,20,3.0,63,2,LIVE
2,40,m,1,2,1,2,2,2,1,2,2,2,2,0.60,62,166,4.0,63,1,LIVE
3,25,m,2,2,1,2,2,1,1,1,1,1,1,1.30,181,181,4.5,57,2,LIVE
4,34,M,1,2,1,2,2,1,1,2,1,2,2,1.00,72,46,4.4,57,1,LIVE

(None, None)

KEEP 

* AGE: The age of the patient.
* SEX: The gender of the patient.

* STEROID: Indicates whether the patient has been treated with steroids.
    --> drop the NaN Value
    --> Or figure out if relationship with Liver?

* ANTIVIRALS: Indicates whether the patient has been treated with antiviral medications.
* FATIGUE: Presence or absence of fatigue as a symptom.
* MALAISE: Presence or absence of malaise, a general feeling of discomfort or unease, as a symptom.
* ANOREXIA: Presence or absence of anorexia, loss of appetite, as a symptom.
    --> Good

* LIVER BIG: Indicates whether the liver is enlarged.
* LIVER FIRM: Indicates whether the liver feels firm upon palpation.
* SPLEEN PALPABLE: Indicates whether the spleen is palpable, meaning it can be felt during a physical examination.
* SPIDERS: Presence or absence of spider nevi (spider-like blood vessels on the skin), which can be a sign of liver disease.
* ASCITES: Presence or absence of ascites, the accumulation of fluid in the abdominal cavity.
* VARICES: Presence or absence of varices, which are swollen veins, often in the esophagus or stomach, that can be a complication of liver disease.
* BILIRUBIN: Levels of bilirubin in the blood, a marker of liver function.
* ALK PHOSPHATE: Alkaline phosphatase levels in the blood, another marker of liver function.
    --> replace with Mode

* SGOT: Serum Glutamic Oxaloacetic Transaminase levels, an enzyme released by the liver.
* ALBUMIN: Levels of albumin in the blood, a protein produced by the liver.
    --> might look into what to do?
    --> KNN 

* PROTIME: Prothrombin time, a measure of blood clotting time.
    --> Drop

* HISTOLOGY: Indicates whether a liver biopsy was performed and the results of the histological examination of the liver tissue.

 AGE : 0 
 SEX : 0 
 STEROID : 1 
 ANTIVIRALS : 0 
 FATIGUE : 0 
 MALAISE : 0 
 ANOREXIA : 0 
 LIVER BIG : 6 
 LIVER FIRM : 7 
 SPLEEN PALPABLE : 3 
 SPIDERS : 3 
 ASCITES : 3 
 VARICES : 3 
 BILIRUBIN : 3 
 ALK PHOSPHATE : 18 
 SGOT : 3 
 ALBUMIN : 9 
 PROTIME : 47 
 HISTOLOGY : 0 
 Class : 0

Clean Sex
Alk Phosphate -> Remove ?

Check overall columns to see if ? 
    If so remove ?
    PROTIME -> Remove ?
    Steroid -> Remove ?

Possible scale 1/2 to 0/1?

Figure out what to do with missing values?
    drop some rows that have missing values

    K-NN / ?? to refit missing data


Understand column names
    We need to figure out what to include

Sex Cleaning

In [661]:
train['SEX'] = train['SEX'].map(lambda x : x if x not in ['m', 'meale', 'Male', 'maled', 'male'] else 'M')
train['SEX'] = train['SEX'].map(lambda x : x if x not in ['Feamle', 'female'] else 'F')

test['SEX'] = test['SEX'].map(lambda x : x if x not in ['m', 'meale', 'Male', 'maled', 'male'] else 'M')
test['SEX'] = test['SEX'].map(lambda x : x if x not in ['Feamle', 'female'] else 'F')

train['SEX'].value_counts()
test['SEX'].value_counts()

SEX
M    47
F     6
Name: count, dtype: int64

In [662]:
list_cols_with_question = []
for col in train.columns:
    if '?' in train[col].value_counts():
        list_cols_with_question.append(col)

In [663]:
train[list_cols_with_question].value_counts()

STEROID  LIVER BIG  LIVER FIRM  SPLEEN PALPABLE  SPIDERS  ASCITES  VARICES  BILIRUBIN  ALK PHOSPHATE  SGOT  ALBUMIN  PROTIME
1        1          1           1                1        2        2        0.90       230            117   3.4      41         1
2        2          1           2                1        2        2        1.30       141            156   3.9      58         1
                    2           2                2        2        2        0.60       120            30    4.0      ?          1
                                                                                       110            145   4.4      70         1
                                                 1        1        2        1.90       ?              114   2.4      ?          1
                                                                                                                               ..
1        2          2           2                1        2        2        0.90       ?              231   4.3      ?          1
                                                                            0.50       62             68    3.8      29         1
                                1                2        2        2        8.00       ?              101   2.2      ?          1
                                                                            1.00       85             75    ?        ?          1
?        2          2           2                2        2        2        0.70       46             52    4.0      80         1
Name: count, Length: 102, dtype: int64

In [664]:
for col in train.columns:
    train[col] = train[col].apply(lambda x : x if x != '?' else np.NaN)

train[list_cols_with_question].value_counts()


for col in test.columns:
    test[col] = test[col].apply(lambda x : x if x != '?' else np.NaN)

test.value_counts()

AGE  SEX  STEROID  ANTIVIRALS  FATIGUE  MALAISE  ANOREXIA  LIVER BIG  LIVER FIRM  SPLEEN PALPABLE  SPIDERS  ASCITES  VARICES  BILIRUBIN  ALK PHOSPHATE  SGOT  ALBUMIN  PROTIME  HISTOLOGY
20   M    1        2           1        1        1         2          2           2                1        1        2        1.00       160            118   2.9      23       2            1
25   F    1        1           2        2        2         2          2           2                2        2        2        0.40       45             18    4.3      70       1            1
64   M    2        1           1        1        2         1          1           2                2        2        2        1.00       80             38    4.3      74       1            1
58   F    2        2           1        2        2         2          1           2                1        2        2        1.40       175            55    2.7      36       1            1
57   M    1        2           1        1        2         2          2           2                1        1        2        4.60       82             55    3.3      30       2            1
54   M    1        2           1        1        2         2          2           2                2        1        2        1.20       85             92    3.1      66       2            1
49   M    1        2           1        1        2         2          2           1                1        2        2        1.40       85             70    3.5      35       2            1
47   M    2        2           2        2        2         2          2           2                1        2        1        2.00       84             23    4.2      66       2            1
42   M    1        2           2        2        2         2          2           2                2        2        2        1.00       85             14    4.0      100      1            1
41   F    2        1           1        1        1         2          2           2                2        2        2        0.70       81             53    5.0      74       1            1
39   M    1        1           1        1        2         2          1           2                2        2        2        2.30       280            98    3.8      40       1            1
38   M    2        1           1        1        1         2          2           2                1        2        2        0.70       125            65    4.2      77       1            1
          1        2           1        1        1         2          2           2                2        1        2        2.00       72             89    2.9      46       1            1
                   1           2        2        2         1          1           2                2        2        2        0.70       70             28    4.2      62       1            1
37   M    2        2           2        2        2         2          2           2                2        2        2        0.70       26             58    4.5      100      1            1
36   M    2        2           2        2        2         2          2           2                2        2        2        0.70       62             224   4.2      100      1            1
35   M    2        2           1        2        2         2          2           2                2        2        2        0.90       58             92    4.3      73       1            1
33   M    1        2           1        1        2         2          2           2                2        1        2        0.70       63             80    3.0      31       2            1
32   M    2        2           2        2        2         2          2           2                2        2        2        0.70       102            64    4.0      90       1            1
                               1        1        1         2          2           2                1        2        1        3.50       215            54    3.4      29       1            1
                   1           1        2        2         2          1           2                1        2        2        1.00       59             249   3.7      54       1            1
31   M    1        2           1        2        2         2          2           2                2        2        2        1.20       75             173   4.2      54       2            1
30   M    2        2           1        2        2         2          1           2                2        2        2        2.20       57             144   4.9      78       1            1
          1        2           2        2        2         2          2           2                2        2        2        0.70       100            31    4.0      100      1            1
                               1        1        2         2          1           2                1        2        2        0.80       147            128   3.9      100      2            1
28   M    1        2           1        1        1         2          1           2                2        2        2        1.60       44             123   4.0      46       1            1
     F    2        2           1        1        2         2          1           2                2        2        2        1.80       191            420   3.3      46       1            1
27   M    2        2           1        1        1         1          1           1                1        2        2        1.20       133            98    4.1      39       1            1
26   F    1        2           2        2        2         2          1           2                2        2        2        0.50       135            29    3.8      60       1            1
72   M    2        1           1        2        2         2          1           2                2        2        2        1.00       115            52    3.4      50       2            1
Name: count, dtype: int64

To drop or Not?

In [665]:
for col in train.columns:
    num = train[col].isna().sum()
    print(f" {col} : {num} ")

 AGE : 0
 SEX : 0
 STEROID : 1
 ANTIVIRALS : 0
 FATIGUE : 0
 MALAISE : 0
 ANOREXIA : 0
 LIVER BIG : 6
 LIVER FIRM : 7
 SPLEEN PALPABLE : 3
 SPIDERS : 3
 ASCITES : 3
 VARICES : 3
 BILIRUBIN : 3
 ALK PHOSPHATE : 18
 SGOT : 3
 ALBUMIN : 9
 PROTIME : 47
 HISTOLOGY : 0
 Class : 0

NaN Replacements
Replace NaN values

STEROID	ANTIVIRALS	FATIGUE	MALAISE	ANOREXIA	LIVER BIG	LIVER FIRM	SPLEEN PALPABLE	SPIDERS	ASCITES	VARICES	HISTOLOGY
    --> Mode

BILIRUBIN	ALK PHOSPHATE	SGOT	ALBUMIN	PROTIME
    --> Mean

In [666]:
test

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,39,M,2,2,1,2,2,2,1,2,2,2,2,0.70,NaN,48,4.4,NaN,1
1,41,F,2,1,1,1,1,2,2,2,2,2,2,0.70,81,53,5.0,74,1
2,28,M,1,2,1,1,1,2,1,2,2,2,2,1.60,44,123,4.0,46,1
3,36,M,1,2,1,1,1,2,1,2,2,2,2,1.00,NaN,45,4.0,57,1
4,32,M,2,2,2,2,2,2,2,2,2,2,2,0.70,102,64,4.0,90,1
5,25,F,1,1,2,2,2,2,2,2,2,2,2,0.40,45,18,4.3,70,1
6,22,M,2,2,2,2,2,2,2,2,2,2,2,0.70,NaN,24,NaN,NaN,2
7,47,M,2,2,2,2,2,2,2,2,1,2,1,2.00,84,23,4.2,66,2
8,20,F,1,2,1,1,1,1,1,1,1,2,2,2.30,150,68,3.9,NaN,1
9,30,M,2,2,1,2,2,2,1,2,2,2,2,2.20,57,144,4.9,78,1
10,66,M,2,2,1,2,2,2,2,2,2,2,2,1.20,102,53,4.3,NaN,1
11,34,M,2,2,2,2,2,2,2,2,2,2,2,NaN,NaN,86,NaN,NaN,1
12,45,M,1,2,1,2,2,2,1,1,2,2,2,1.20,81,65,3.0,NaN,1
13,36,M,1,2,1,1,1,1,1,2,1,2,1,1.70,295,60,2.7,NaN,2
14,78,M,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,NaN,1
15,30,M,1,2,1,1,2,2,1,2,1,2,2,0.80,147,128,3.9,100,2
16,32,M,2,1,1,2,2,2,1,2,1,2,2,1.00,59,249,3.7,54,1
17,72,M,2,1,1,2,2,2,1,2,2,2,2,1.00,115,52,3.4,50,2
18,49,M,1,2,1,1,2,2,2,1,1,2,2,1.40,85,70,3.5,35,2
19,57,M,2,2,1,1,1,2,2,2,1,1,2,4.10,NaN,48,2.6,73,1
20,42,M,1,2,2,2,2,2,2,2,2,2,2,1.00,85,14,4.0,100,1
21,37,M,2,2,1,2,2,2,2,2,1,2,2,0.60,67,28,4.2,NaN,1
22,38,M,2,1,1,1,1,2,2,2,1,2,2,0.70,125,65,4.2,77,1
23,30,M,1,2,2,2,2,2,2,2,2,2,2,0.70,100,31,4.0,100,1
24,24,M,2,2,2,2,2,2,2,2,2,2,2,0.80,82,39,4.3,NaN,1
25,58,F,2,2,1,2,2,2,1,2,1,2,2,1.40,175,55,2.7,36,1
26,33,M,1,2,1,1,2,2,2,2,2,1,2,0.70,63,80,3.0,31,2
27,64,M,2,1,1,1,2,1,1,2,2,2,2,1.00,80,38,4.3,74,1
28,38,M,1,2,1,1,1,2,1,2,1,1,1,1.20,118,16,2.8,NaN,2
29,42,M,2,2,2,2,2,2,2,1,2,2,2,1.50,85,40,NaN,NaN,2
30,57,M,1,2,1,1,2,2,2,2,1,1,2,4.60,82,55,3.3,30,2
31,26,F,1,2,2,2,2,2,1,2,2,2,2,0.50,135,29,3.8,60,1
32,62,M,1,2,1,1,2,NaN,NaN,2,2,2,2,1.00,NaN,60,NaN,NaN,1
33,61,M,1,2,1,1,2,1,1,2,1,2,2,0.80,75,20,4.1,NaN,2
34,32,M,2,2,1,1,1,2,2,2,1,2,1,3.50,215,54,3.4,29,1
35,47,M,1,1,2,2,2,2,2,2,2,2,2,NaN,NaN,60,NaN,NaN,1
36,70,M,1,2,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1.70,109,528,2.8,35,2
37,38,M,1,2,1,1,1,2,2,2,2,1,2,2.00,72,89,2.9,46,1
38,28,F,2,2,1,1,2,2,1,2,2,2,2,1.80,191,420,3.3,46,1
39,20,M,1,2,1,1,1,2,2,2,1,1,2,1.00,160,118,2.9,23,2
40,34,M,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
41,39,M,1,1,1,1,2,2,1,2,2,2,2,2.30,280,98,3.8,40,1
42,37,M,2,2,2,2,2,2,2,2,2,2,2,0.70,26,58,4.5,100,1
43,54,M,1,2,1,1,2,2,2,2,2,1,2,1.20,85,92,3.1,66,2
44,36,M,2,2,2,2,2,2,2,2,2,2,2,0.70,62,224,4.2,100,1
45,45,M,1,2,1,1,1,2,2,2,2,2,2,2.30,NaN,648,NaN,NaN,2
46,27,M,2,2,1,1,1,1,1,1,1,2,2,1.20,133,98,4.1,39,1
47,41,M,2,2,1,2,2,2,1,1,1,2,1,4.20,65,120,3.4,NaN,2
48,25,M,2,2,2,2,2,2,2,2,2,2,2,0.60,NaN,34,6.4,NaN,2
49,35,M,2,2,1,2,2,2,2,2,2,2,2,0.90,58,92,4.3,73,1
50,33,M,2,2,2,2,2,NaN,NaN,2,2,2,2,1.00,NaN,60,4.0,NaN,2
51,31,M,1,2,1,2,2,2,2,2,2,2,2,1.20,75,173,4.2,54,2
52,38,M,1,1,2,2,2,1,1,2,2,2,2,0.70,70,28,4.2,62,1

In [667]:
train.dtypes

AGE                 int64
SEX                object
STEROID            object
ANTIVIRALS          int64
FATIGUE             int64
MALAISE             int64
ANOREXIA            int64
LIVER BIG          object
LIVER FIRM         object
SPLEEN PALPABLE    object
SPIDERS            object
ASCITES            object
VARICES            object
BILIRUBIN          object
ALK PHOSPHATE      object
SGOT               object
ALBUMIN            object
PROTIME            object
HISTOLOGY           int64
Class              object
dtype: object

In [668]:
list_of_mode = ['STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE', 'ANOREXIA', 'LIVER BIG',  'LIVER FIRM', 'SPLEEN PALPABLE', 'SPIDERS', 'ASCITES',	'VARICES', 'HISTOLOGY']
list_of_mean = ['BILIRUBIN', 'ALK PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME']

In [669]:
# Convert to floats
for col in list_of_mean:
    train[col] = pd.to_numeric(train[col])

for col in ['HISTOLOGY', 'STEROID', 'ANTIVIRALS']:
    train[col] = train[col].astype('object')

# Convert to floats
for col in list_of_mean:
    test[col] = pd.to_numeric(test[col])

for col in ['HISTOLOGY', 'STEROID', 'ANTIVIRALS']:
    test[col] = test[col].astype('object')

In [670]:
train.dtypes
test.dtypes

AGE                  int64
SEX                 object
STEROID             object
ANTIVIRALS          object
FATIGUE             object
MALAISE             object
ANOREXIA            object
LIVER BIG           object
LIVER FIRM          object
SPLEEN PALPABLE     object
SPIDERS             object
ASCITES             object
VARICES             object
BILIRUBIN          float64
ALK PHOSPHATE      float64
SGOT               float64
ALBUMIN            float64
PROTIME            float64
HISTOLOGY           object
dtype: object

In [671]:
for col in list_of_mode:
    train[col].fillna(train[col].mode().iloc[0], inplace=True)

for col in list_of_mean:
    train[col].fillna(train[col].mean(), inplace=True)

train


for col in list_of_mode:
    test[col].fillna(test[col].mode().iloc[0], inplace=True)

for col in list_of_mean:
    test[col].fillna(test[col].mean(), inplace=True)

test

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,39,M,2,2,1,2,2,2,1,2,2,2,2,0.700,105.142857,48.000000,4.400000,61.030303,1
1,41,F,2,1,1,1,1,2,2,2,2,2,2,0.700,81.000000,53.000000,5.000000,74.000000,1
2,28,M,1,2,1,1,1,2,1,2,2,2,2,1.600,44.000000,123.000000,4.000000,46.000000,1
3,36,M,1,2,1,1,1,2,1,2,2,2,2,1.000,105.142857,45.000000,4.000000,57.000000,1
4,32,M,2,2,2,2,2,2,2,2,2,2,2,0.700,102.000000,64.000000,4.000000,90.000000,1
5,25,F,1,1,2,2,2,2,2,2,2,2,2,0.400,45.000000,18.000000,4.300000,70.000000,1
6,22,M,2,2,2,2,2,2,2,2,2,2,2,0.700,105.142857,24.000000,3.826087,61.030303,2
7,47,M,2,2,2,2,2,2,2,2,1,2,1,2.000,84.000000,23.000000,4.200000,66.000000,2
8,20,F,1,2,1,1,1,1,1,1,1,2,2,2.300,150.000000,68.000000,3.900000,61.030303,1
9,30,M,2,2,1,2,2,2,1,2,2,2,2,2.200,57.000000,144.000000,4.900000,78.000000,1
10,66,M,2,2,1,2,2,2,2,2,2,2,2,1.200,102.000000,53.000000,4.300000,61.030303,1
11,34,M,2,2,2,2,2,2,2,2,2,2,2,1.378,105.142857,86.000000,3.826087,61.030303,1
12,45,M,1,2,1,2,2,2,1,1,2,2,2,1.200,81.000000,65.000000,3.000000,61.030303,1
13,36,M,1,2,1,1,1,1,1,2,1,2,1,1.700,295.000000,60.000000,2.700000,61.030303,2
14,78,M,2,2,1,2,2,2,2,2,2,2,2,0.700,96.000000,32.000000,4.000000,61.030303,1
15,30,M,1,2,1,1,2,2,1,2,1,2,2,0.800,147.000000,128.000000,3.900000,100.000000,2
16,32,M,2,1,1,2,2,2,1,2,1,2,2,1.000,59.000000,249.000000,3.700000,54.000000,1
17,72,M,2,1,1,2,2,2,1,2,2,2,2,1.000,115.000000,52.000000,3.400000,50.000000,2
18,49,M,1,2,1,1,2,2,2,1,1,2,2,1.400,85.000000,70.000000,3.500000,35.000000,2
19,57,M,2,2,1,1,1,2,2,2,1,1,2,4.100,105.142857,48.000000,2.600000,73.000000,1
20,42,M,1,2,2,2,2,2,2,2,2,2,2,1.000,85.000000,14.000000,4.000000,100.000000,1
21,37,M,2,2,1,2,2,2,2,2,1,2,2,0.600,67.000000,28.000000,4.200000,61.030303,1
22,38,M,2,1,1,1,1,2,2,2,1,2,2,0.700,125.000000,65.000000,4.200000,77.000000,1
23,30,M,1,2,2,2,2,2,2,2,2,2,2,0.700,100.000000,31.000000,4.000000,100.000000,1
24,24,M,2,2,2,2,2,2,2,2,2,2,2,0.800,82.000000,39.000000,4.300000,61.030303,1
25,58,F,2,2,1,2,2,2,1,2,1,2,2,1.400,175.000000,55.000000,2.700000,36.000000,1
26,33,M,1,2,1,1,2,2,2,2,2,1,2,0.700,63.000000,80.000000,3.000000,31.000000,2
27,64,M,2,1,1,1,2,1,1,2,2,2,2,1.000,80.000000,38.000000,4.300000,74.000000,1
28,38,M,1,2,1,1,1,2,1,2,1,1,1,1.200,118.000000,16.000000,2.800000,61.030303,2
29,42,M,2,2,2,2,2,2,2,1,2,2,2,1.500,85.000000,40.000000,3.826087,61.030303,2
30,57,M,1,2,1,1,2,2,2,2,1,1,2,4.600,82.000000,55.000000,3.300000,30.000000,2
31,26,F,1,2,2,2,2,2,1,2,2,2,2,0.500,135.000000,29.000000,3.800000,60.000000,1
32,62,M,1,2,1,1,2,2,2,2,2,2,2,1.000,105.142857,60.000000,3.826087,61.030303,1
33,61,M,1,2,1,1,2,1,1,2,1,2,2,0.800,75.000000,20.000000,4.100000,61.030303,2
34,32,M,2,2,1,1,1,2,2,2,1,2,1,3.500,215.000000,54.000000,3.400000,29.000000,1
35,47,M,1,1,2,2,2,2,2,2,2,2,2,1.378,105.142857,60.000000,3.826087,61.030303,1
36,70,M,1,2,1,1,1,2,2,2,2,2,2,1.700,109.000000,528.000000,2.800000,35.000000,2
37,38,M,1,2,1,1,1,2,2,2,2,1,2,2.000,72.000000,89.000000,2.900000,46.000000,1
38,28,F,2,2,1,1,2,2,1,2,2,2,2,1.800,191.000000,420.000000,3.300000,46.000000,1
39,20,M,1,2,1,1,1,2,2,2,1,1,2,1.000,160.000000,118.000000,2.900000,23.000000,2
40,34,M,1,2,1,2,2,2,2,2,2,2,2,1.378,105.142857,96.480769,3.826087,61.030303,1
41,39,M,1,1,1,1,2,2,1,2,2,2,2,2.300,280.000000,98.000000,3.800000,40.000000,1
42,37,M,2,2,2,2,2,2,2,2,2,2,2,0.700,26.000000,58.000000,4.500000,100.000000,1
43,54,M,1,2,1,1,2,2,2,2,2,1,2,1.200,85.000000,92.000000,3.100000,66.000000,2
44,36,M,2,2,2,2,2,2,2,2,2,2,2,0.700,62.000000,224.000000,4.200000,100.000000,1
45,45,M,1,2,1,1,1,2,2,2,2,2,2,2.300,105.142857,648.000000,3.826087,61.030303,2
46,27,M,2,2,1,1,1,1,1,1,1,2,2,1.200,133.000000,98.000000,4.100000,39.000000,1
47,41,M,2,2,1,2,2,2,1,1,1,2,1,4.200,65.000000,120.000000,3.400000,61.030303,2
48,25,M,2,2,2,2,2,2,2,2,2,2,2,0.600,105.142857,34.000000,6.400000,61.030303,2
49,35,M,2,2,1,2,2,2,2,2,2,2,2,0.900,58.000000,92.000000,4.300000,73.000000,1
50,33,M,2,2,2,2,2,2,2,2,2,2,2,1.000,105.142857,60.000000,4.000000,61.030303,2
51,31,M,1,2,1,2,2,2,2,2,2,2,2,1.200,75.000000,173.000000,4.200000,54.000000,2
52,38,M,1,1,2,2,2,1,1,2,2,2,2,0.700,70.000000,28.000000,4.200000,62.000000,1

In [672]:
for col in train.columns:
    num = train[col].isna().sum()
    print(f" {col} : {num} ")

for col in test.columns:
    num = test[col].isna().sum()
    print(f" {col} : {num} ")

 AGE : 0
 SEX : 0
 STEROID : 0
 ANTIVIRALS : 0
 FATIGUE : 0
 MALAISE : 0
 ANOREXIA : 0
 LIVER BIG : 0
 LIVER FIRM : 0
 SPLEEN PALPABLE : 0
 SPIDERS : 0
 ASCITES : 0
 VARICES : 0
 BILIRUBIN : 0
 ALK PHOSPHATE : 0
 SGOT : 0
 ALBUMIN : 0
 PROTIME : 0
 HISTOLOGY : 0
 Class : 0
 AGE : 0
 SEX : 0
 STEROID : 0
 ANTIVIRALS : 0
 FATIGUE : 0
 MALAISE : 0
 ANOREXIA : 0
 LIVER BIG : 0
 LIVER FIRM : 0
 SPLEEN PALPABLE : 0
 SPIDERS : 0
 ASCITES : 0
 VARICES : 0
 BILIRUBIN : 0
 ALK PHOSPHATE : 0
 SGOT : 0
 ALBUMIN : 0
 PROTIME : 0
 HISTOLOGY : 0

In [673]:
from sklearn.preprocessing import OneHotEncoder

SEX = train[['SEX']]

OneHot = OneHotEncoder(drop='first')
OneHot.fit(SEX)
SEX_onehot = OneHot.transform(SEX).toarray()

SEX_df = pd.DataFrame(SEX_onehot, columns=OneHot.get_feature_names_out(), index=SEX.index)
SEX_df['SEX_M']

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
97     1.0
98     1.0
99     1.0
100    1.0
101    1.0
Name: SEX_M, Length: 102, dtype: float64

In [674]:
SEX = test[['SEX']]

OneHot = OneHotEncoder(drop='first')
OneHot.fit(SEX)
SEX_onehot = OneHot.transform(SEX).toarray()

SEX_test = pd.DataFrame(SEX_onehot, columns=OneHot.get_feature_names_out(), index=SEX.index)
SEX_test['SEX_M']

0     1.0
1     0.0
2     1.0
3     1.0
4     1.0
5     0.0
6     1.0
7     1.0
8     0.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    0.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    0.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    0.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
Name: SEX_M, dtype: float64

In [675]:
# Convert to floats
for col in list_of_mean:
    train[col] = pd.to_numeric(train[col])

for col in list_of_mode:
    train[col] = train[col].astype('object')

# Convert to floats
for col in list_of_mean:
    test[col] = pd.to_numeric(test[col])

for col in list_of_mode:
    test[col] = test[col].astype('object')

In [676]:
train.dtypes

AGE                  int64
SEX                 object
STEROID             object
ANTIVIRALS          object
FATIGUE             object
MALAISE             object
ANOREXIA            object
LIVER BIG           object
LIVER FIRM          object
SPLEEN PALPABLE     object
SPIDERS             object
ASCITES             object
VARICES             object
BILIRUBIN          float64
ALK PHOSPHATE      float64
SGOT               float64
ALBUMIN            float64
PROTIME            float64
HISTOLOGY           object
Class               object
dtype: object

In [677]:
for col in list_of_mode:
    train[col] = train[col].map(lambda x : str(x).replace("2", "0"))

for col in list_of_mode:
    test[col] = test[col].map(lambda x : str(x).replace("2", "0"))

In [678]:
train.dtypes

AGE                  int64
SEX                 object
STEROID             object
ANTIVIRALS          object
FATIGUE             object
MALAISE             object
ANOREXIA            object
LIVER BIG           object
LIVER FIRM          object
SPLEEN PALPABLE     object
SPIDERS             object
ASCITES             object
VARICES             object
BILIRUBIN          float64
ALK PHOSPHATE      float64
SGOT               float64
ALBUMIN            float64
PROTIME            float64
HISTOLOGY           object
Class               object
dtype: object

In [679]:
from sklearn.preprocessing import MinMaxScaler

numerics = train.select_dtypes(include=np.number)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(numerics)

numerics_df = pd.DataFrame(scaled, columns=numerics.columns)

cats = train.drop(numerics.columns, axis=1)

merge = pd.merge(right=numerics_df, left=cats, right_index=True, left_index=True)

train = merge[[x for x in merge.columns if x != 'Class'] + ['Class']]
display(train.head(50))

,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,HISTOLOGY,AGE,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,Class
0,M,1,0,1,1,0,0,1,0,1,1,1,0,0.661290,0.584416,0.411504,0.541667,0.187500,0.310000,DIE
1,M,0,0,1,0,0,0,1,1,1,0,1,0,0.709677,0.090909,0.333702,0.022727,0.281250,0.630000,LIVE
2,M,1,0,1,0,0,0,1,0,0,0,0,1,0.532258,0.038961,0.141593,0.575758,0.593750,0.630000,LIVE
3,M,0,0,1,0,0,1,1,1,1,1,1,0,0.290323,0.129870,0.668142,0.632576,0.750000,0.570000,LIVE
4,M,1,0,1,0,0,1,1,0,1,0,0,1,0.435484,0.090909,0.185841,0.121212,0.718750,0.570000,LIVE
5,M,1,1,1,1,1,1,1,0,0,0,0,0,0.532258,0.038961,0.044248,0.208333,0.656250,0.670000,LIVE
6,M,1,1,0,0,0,0,0,0,0,0,0,1,0.725806,0.051948,0.199115,0.155303,0.593750,0.210000,LIVE
7,M,0,0,0,0,0,0,0,0,0,0,0,1,0.387097,0.090909,0.243363,0.022727,0.593750,1.000000,LIVE
8,M,1,1,1,1,0,0,0,0,0,0,0,1,0.709677,0.090909,0.212389,0.166667,0.781250,0.520000,LIVE
9,F,0,0,1,1,0,0,1,0,1,0,0,1,0.887097,0.129870,0.491150,0.537879,0.562500,0.580000,LIVE
10,M,0,0,1,1,1,0,1,0,1,1,1,0,0.370968,0.285714,0.597345,0.189394,0.218750,0.623455,DIE
11,M,1,0,1,0,0,1,1,0,0,0,0,1,0.870968,0.129870,0.212389,0.041667,0.531250,1.000000,LIVE
12,M,0,0,0,0,0,0,1,1,1,0,0,0,0.693548,0.090909,0.243363,0.231061,0.593750,0.720000,LIVE
13,M,1,0,1,1,1,0,0,1,0,0,0,0,0.387097,1.000000,0.333702,0.329545,0.031250,0.623455,DIE
14,M,0,0,0,0,0,0,0,0,0,0,0,1,0.516129,0.090909,0.243363,0.022727,0.593750,0.623455,LIVE
15,F,1,1,0,0,0,0,1,0,0,0,0,1,0.435484,0.038961,0.000000,0.037879,0.593750,0.760000,LIVE
16,M,0,1,0,0,0,0,0,0,0,0,0,1,0.387097,0.051948,0.070796,0.143939,0.593750,0.800000,LIVE
17,F,1,0,1,0,0,1,1,1,1,0,0,0,0.693548,0.077922,0.884956,0.390152,0.406250,0.410000,LIVE
18,M,1,0,1,1,0,0,1,1,1,0,0,0,0.838710,0.155844,0.340708,0.541667,0.468750,0.380000,DIE
19,M,0,0,0,0,0,0,0,0,0,0,0,0,0.467742,0.038961,0.398230,0.060606,0.593750,0.623455,LIVE
20,M,1,0,1,0,0,0,1,0,0,0,0,0,0.322581,0.272727,0.610619,0.806818,0.281250,0.660000,LIVE
21,M,1,0,1,1,1,0,1,1,1,0,1,0,0.709677,0.558442,0.818584,0.965909,0.562500,0.510000,LIVE
22,M,0,1,1,0,0,0,1,0,0,0,0,1,0.548387,0.077922,0.225664,0.174242,0.562500,0.520000,LIVE
23,F,1,0,1,0,0,0,0,1,1,0,1,0,0.741935,0.155844,0.225664,0.018939,0.625000,0.480000,LIVE
24,M,0,0,0,0,0,0,0,0,0,0,0,1,0.258065,0.558442,0.115044,0.007576,0.781250,0.623455,LIVE
25,M,0,0,1,0,0,0,0,0,0,0,0,1,0.516129,0.090909,0.017699,0.003788,0.593750,0.540000,LIVE
26,M,1,1,1,1,1,0,1,0,1,0,0,1,0.677419,0.038961,0.243363,0.128788,0.500000,0.623455,LIVE
27,M,1,0,1,0,0,1,0,0,0,0,0,1,0.693548,0.077922,0.464602,0.106061,0.437500,0.623455,LIVE
28,M,0,0,1,1,0,0,1,1,1,1,0,0,0.935484,0.000000,0.663717,0.147727,0.250000,0.740000,LIVE
29,M,0,0,0,0,0,1,1,0,1,0,0,0,0.709677,0.064935,0.333702,0.071970,0.750000,0.623455,LIVE
30,F,0,0,1,0,0,0,0,0,0,0,0,0,1.000000,0.376623,0.393805,0.462121,0.535282,0.623455,LIVE
31,M,1,0,0,0,0,0,1,0,1,0,0,1,0.483871,0.038961,0.221239,0.250000,0.531250,0.623455,LIVE
32,M,0,1,1,0,0,0,1,1,0,0,0,1,0.532258,0.116883,0.243363,0.064394,0.593750,1.000000,LIVE
33,M,1,1,0,0,0,1,1,0,0,0,0,1,0.516129,0.129870,0.212389,0.060606,0.718750,0.850000,LIVE
34,M,1,0,0,0,0,0,0,0,0,0,0,0,0.209677,0.077922,0.261062,0.522727,0.593750,0.623455,LIVE
35,M,0,0,1,0,0,0,1,1,0,1,1,0,0.693548,0.324675,0.553097,0.231061,0.093750,0.320000,DIE
36,M,1,0,1,1,1,0,0,1,1,0,1,0,0.564516,0.558442,0.333702,0.155303,0.375000,0.623455,DIE
37,M,0,0,1,0,0,1,1,0,0,0,0,0,0.758065,0.376623,0.243363,0.053030,0.531250,0.623455,LIVE
38,M,0,0,0,0,0,0,0,0,0,0,0,0,0.500000,0.051948,0.101770,0.106061,0.625000,0.850000,LIVE
39,M,0,0,0,0,0,0,0,0,0,0,0,1,0.435484,0.090909,0.333702,0.704545,0.593750,0.623455,LIVE
40,M,0,0,0,0,0,0,0,0,0,0,0,1,0.419355,0.090909,0.070796,0.287879,0.718750,0.600000,LIVE
41,M,0,0,1,1,0,0,0,0,0,0,0,1,0.338710,0.051948,0.194690,0.363636,0.718750,0.623455,LIVE
42,M,1,0,1,1,0,1,1,0,1,0,0,1,0.435484,0.324675,0.429204,0.636364,0.535282,0.623455,DIE
43,M,0,0,0,0,0,0,0,0,0,0,0,1,0.338710,0.051948,0.243363,0.064394,0.875000,0.623455,LIVE
44,F,1,0,0,0,0,1,0,0,0,0,0,1,0.370968,0.090909,0.243363,0.015152,0.593750,0.623455,LIVE
45,F,0,1,1,0,0,0,0,0,0,0,0,1,0.241935,0.077922,0.079646,0.022727,0.656250,0.640000,LIVE
46,F,1,0,1,1,0,0,0,1,0,0,0,1,0.612903,0.090909,0.243363,0.231061,0.535282,0.623455,LIVE
47,M,0,0,1,1,1,0,0,0,0,0,0,1,0.709677,0.077922,0.203540,0.973485,0.718750,0.623455,LIVE
48,M,0,1,0,0,0,0,0,0,0,0,0,0,0.612903,0.129870,0.243363,0.113636,0.656250,0.850000,LIVE
49,M,0,0,1,1,1,0,0,0,1,1,1,0,0.629032,0.948052,0.333702,0.863636,0.375000,0.500000,DIE

In [680]:
numerics = test.select_dtypes(include=np.number)

scaled = scaler.transform(numerics)

numerics_df = pd.DataFrame(scaled, columns=numerics.columns)

cats = test.drop(numerics.columns, axis=1)

merge = pd.merge(right=numerics_df, left=cats, right_index=True, left_index=True)

test = merge[[x for x in merge.columns if x != 'Class']]
test

,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,HISTOLOGY,AGE,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME
0,M,0,0,1,0,0,0,1,0,0,0,0,1,0.516129,0.051948,0.332491,0.128788,0.718750,0.610303
1,F,0,1,1,1,1,0,0,0,0,0,0,1,0.548387,0.051948,0.225664,0.147727,0.906250,0.740000
2,M,1,0,1,1,1,0,1,0,0,0,0,1,0.338710,0.168831,0.061947,0.412879,0.593750,0.460000
3,M,1,0,1,1,1,0,1,0,0,0,0,1,0.467742,0.090909,0.332491,0.117424,0.593750,0.570000
4,M,0,0,0,0,0,0,0,0,0,0,0,1,0.403226,0.051948,0.318584,0.189394,0.593750,0.900000
5,F,1,1,0,0,0,0,0,0,0,0,0,1,0.290323,0.012987,0.066372,0.015152,0.687500,0.700000
6,M,0,0,0,0,0,0,0,0,0,0,0,0,0.241935,0.051948,0.332491,0.037879,0.539402,0.610303
7,M,0,0,0,0,0,0,0,0,1,0,1,0,0.645161,0.220779,0.238938,0.034091,0.656250,0.660000
8,F,1,0,1,1,1,1,1,1,1,0,0,1,0.209677,0.259740,0.530973,0.204545,0.562500,0.610303
9,M,0,0,1,0,0,0,1,0,0,0,0,1,0.370968,0.246753,0.119469,0.492424,0.875000,0.780000
10,M,0,0,1,0,0,0,0,0,0,0,0,1,0.951613,0.116883,0.318584,0.147727,0.687500,0.610303
11,M,0,0,0,0,0,0,0,0,0,0,0,1,0.435484,0.140000,0.332491,0.272727,0.539402,0.610303
12,M,1,0,1,0,0,0,1,1,0,0,0,1,0.612903,0.116883,0.225664,0.193182,0.281250,0.610303
13,M,1,0,1,1,1,1,1,0,1,0,1,0,0.467742,0.181818,1.172566,0.174242,0.187500,0.610303
14,M,0,0,1,0,0,0,0,0,0,0,0,1,1.145161,0.051948,0.292035,0.068182,0.593750,0.610303
15,M,1,0,1,1,0,0,1,0,1,0,0,0,0.370968,0.064935,0.517699,0.431818,0.562500,1.000000
16,M,0,1,1,0,0,0,1,0,1,0,0,1,0.403226,0.090909,0.128319,0.890152,0.500000,0.540000
17,M,0,1,1,0,0,0,1,0,0,0,0,0,1.048387,0.090909,0.376106,0.143939,0.406250,0.500000
18,M,1,0,1,1,0,0,0,1,1,0,0,0,0.677419,0.142857,0.243363,0.212121,0.437500,0.350000
19,M,0,0,1,1,1,0,0,0,1,1,0,1,0.806452,0.493506,0.332491,0.128788,0.156250,0.730000
20,M,1,0,0,0,0,0,0,0,0,0,0,1,0.564516,0.090909,0.243363,0.000000,0.593750,1.000000
21,M,0,0,1,0,0,0,0,0,1,0,0,1,0.483871,0.038961,0.163717,0.053030,0.656250,0.610303
22,M,0,1,1,1,1,0,0,0,1,0,0,1,0.500000,0.051948,0.420354,0.193182,0.656250,0.770000
23,M,1,0,0,0,0,0,0,0,0,0,0,1,0.370968,0.051948,0.309735,0.064394,0.593750,1.000000
24,M,0,0,0,0,0,0,0,0,0,0,0,1,0.274194,0.064935,0.230088,0.094697,0.687500,0.610303
25,F,0,0,1,0,0,0,1,0,1,0,0,1,0.822581,0.142857,0.641593,0.155303,0.187500,0.360000
26,M,1,0,1,1,0,0,0,0,0,1,0,0,0.419355,0.051948,0.146018,0.250000,0.281250,0.310000
27,M,0,1,1,1,0,1,1,0,0,0,0,1,0.919355,0.090909,0.221239,0.090909,0.687500,0.740000
28,M,1,0,1,1,1,0,1,0,1,1,1,0,0.500000,0.116883,0.389381,0.007576,0.218750,0.610303
29,M,0,0,0,0,0,0,0,1,0,0,0,0,0.564516,0.155844,0.243363,0.098485,0.539402,0.610303
30,M,1,0,1,1,0,0,0,0,1,1,0,0,0.806452,0.558442,0.230088,0.155303,0.375000,0.300000
31,F,1,0,0,0,0,0,1,0,0,0,0,1,0.306452,0.025974,0.464602,0.056818,0.531250,0.600000
32,M,1,0,1,1,0,0,0,0,0,0,0,1,0.887097,0.090909,0.332491,0.174242,0.539402,0.610303
33,M,1,0,1,1,0,1,1,0,1,0,0,0,0.870968,0.064935,0.199115,0.022727,0.625000,0.610303
34,M,0,0,1,1,1,0,0,0,1,0,1,1,0.403226,0.415584,0.818584,0.151515,0.406250,0.290000
35,M,1,1,0,0,0,0,0,0,0,0,0,1,0.645161,0.140000,0.332491,0.174242,0.539402,0.610303
36,M,1,0,1,1,1,0,0,0,0,0,0,0,1.016129,0.181818,0.349558,1.946970,0.218750,0.350000
37,M,1,0,1,1,1,0,0,0,0,1,0,1,0.500000,0.220779,0.185841,0.284091,0.250000,0.460000
38,F,0,0,1,1,0,0,1,0,0,0,0,1,0.338710,0.194805,0.712389,1.537879,0.375000,0.460000
39,M,1,0,1,1,1,0,0,0,1,1,0,0,0.209677,0.090909,0.575221,0.393939,0.250000,0.230000
40,M,1,0,1,0,0,0,0,0,0,0,0,1,0.435484,0.140000,0.332491,0.312427,0.539402,0.610303
41,M,1,1,1,1,0,0,1,0,0,0,0,1,0.516129,0.259740,1.106195,0.318182,0.531250,0.400000
42,M,0,0,0,0,0,0,0,0,0,0,0,1,0.483871,0.051948,-0.017699,0.166667,0.750000,1.000000
43,M,1,0,1,1,0,0,0,0,0,1,0,0,0.758065,0.116883,0.243363,0.295455,0.312500,0.660000
44,M,0,0,0,0,0,0,0,0,0,0,0,1,0.467742,0.051948,0.141593,0.795455,0.656250,1.000000
45,M,1,0,1,1,1,0,0,0,0,0,0,0,0.612903,0.259740,0.332491,2.401515,0.539402,0.610303
46,M,0,0,1,1,1,1,1,1,1,0,0,1,0.322581,0.116883,0.455752,0.318182,0.625000,0.390000
47,M,0,0,1,0,0,0,1,1,1,0,1,0,0.548387,0.506494,0.154867,0.401515,0.406250,0.610303
48,M,0,0,0,0,0,0,0,0,0,0,0,0,0.290323,0.038961,0.332491,0.075758,1.343750,0.610303
49,M,0,0,1,0,0,0,0,0,0,0,0,1,0.451613,0.077922,0.123894,0.295455,0.687500,0.730000
50,M,0,0,0,0,0,0,0,0,0,0,0,0,0.419355,0.090909,0.332491,0.174242,0.593750,0.610303
51,M,1,0,1,0,0,0,0,0,0,0,0,0,0.387097,0.116883,0.199115,0.602273,0.656250,0.540000
52,M,1,1,0,0,0,1,1,0,0,0,0,1,0.500000,0.051948,0.176991,0.053030,0.656250,0.620000

In [681]:
train['OneHotSex'] = SEX_df
train.drop('SEX', axis=1, inplace=True)

In [682]:
test['OneHotSex'] = SEX_test
test.drop('SEX', axis=1, inplace=True)
test

,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,HISTOLOGY,AGE,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,OneHotSex
0,0,0,1,0,0,0,1,0,0,0,0,1,0.516129,0.051948,0.332491,0.128788,0.718750,0.610303,1.0
1,0,1,1,1,1,0,0,0,0,0,0,1,0.548387,0.051948,0.225664,0.147727,0.906250,0.740000,0.0
2,1,0,1,1,1,0,1,0,0,0,0,1,0.338710,0.168831,0.061947,0.412879,0.593750,0.460000,1.0
3,1,0,1,1,1,0,1,0,0,0,0,1,0.467742,0.090909,0.332491,0.117424,0.593750,0.570000,1.0
4,0,0,0,0,0,0,0,0,0,0,0,1,0.403226,0.051948,0.318584,0.189394,0.593750,0.900000,1.0
5,1,1,0,0,0,0,0,0,0,0,0,1,0.290323,0.012987,0.066372,0.015152,0.687500,0.700000,0.0
6,0,0,0,0,0,0,0,0,0,0,0,0,0.241935,0.051948,0.332491,0.037879,0.539402,0.610303,1.0
7,0,0,0,0,0,0,0,0,1,0,1,0,0.645161,0.220779,0.238938,0.034091,0.656250,0.660000,1.0
8,1,0,1,1,1,1,1,1,1,0,0,1,0.209677,0.259740,0.530973,0.204545,0.562500,0.610303,0.0
9,0,0,1,0,0,0,1,0,0,0,0,1,0.370968,0.246753,0.119469,0.492424,0.875000,0.780000,1.0
10,0,0,1,0,0,0,0,0,0,0,0,1,0.951613,0.116883,0.318584,0.147727,0.687500,0.610303,1.0
11,0,0,0,0,0,0,0,0,0,0,0,1,0.435484,0.140000,0.332491,0.272727,0.539402,0.610303,1.0
12,1,0,1,0,0,0,1,1,0,0,0,1,0.612903,0.116883,0.225664,0.193182,0.281250,0.610303,1.0
13,1,0,1,1,1,1,1,0,1,0,1,0,0.467742,0.181818,1.172566,0.174242,0.187500,0.610303,1.0
14,0,0,1,0,0,0,0,0,0,0,0,1,1.145161,0.051948,0.292035,0.068182,0.593750,0.610303,1.0
15,1,0,1,1,0,0,1,0,1,0,0,0,0.370968,0.064935,0.517699,0.431818,0.562500,1.000000,1.0
16,0,1,1,0,0,0,1,0,1,0,0,1,0.403226,0.090909,0.128319,0.890152,0.500000,0.540000,1.0
17,0,1,1,0,0,0,1,0,0,0,0,0,1.048387,0.090909,0.376106,0.143939,0.406250,0.500000,1.0
18,1,0,1,1,0,0,0,1,1,0,0,0,0.677419,0.142857,0.243363,0.212121,0.437500,0.350000,1.0
19,0,0,1,1,1,0,0,0,1,1,0,1,0.806452,0.493506,0.332491,0.128788,0.156250,0.730000,1.0
20,1,0,0,0,0,0,0,0,0,0,0,1,0.564516,0.090909,0.243363,0.000000,0.593750,1.000000,1.0
21,0,0,1,0,0,0,0,0,1,0,0,1,0.483871,0.038961,0.163717,0.053030,0.656250,0.610303,1.0
22,0,1,1,1,1,0,0,0,1,0,0,1,0.500000,0.051948,0.420354,0.193182,0.656250,0.770000,1.0
23,1,0,0,0,0,0,0,0,0,0,0,1,0.370968,0.051948,0.309735,0.064394,0.593750,1.000000,1.0
24,0,0,0,0,0,0,0,0,0,0,0,1,0.274194,0.064935,0.230088,0.094697,0.687500,0.610303,1.0
25,0,0,1,0,0,0,1,0,1,0,0,1,0.822581,0.142857,0.641593,0.155303,0.187500,0.360000,0.0
26,1,0,1,1,0,0,0,0,0,1,0,0,0.419355,0.051948,0.146018,0.250000,0.281250,0.310000,1.0
27,0,1,1,1,0,1,1,0,0,0,0,1,0.919355,0.090909,0.221239,0.090909,0.687500,0.740000,1.0
28,1,0,1,1,1,0,1,0,1,1,1,0,0.500000,0.116883,0.389381,0.007576,0.218750,0.610303,1.0
29,0,0,0,0,0,0,0,1,0,0,0,0,0.564516,0.155844,0.243363,0.098485,0.539402,0.610303,1.0
30,1,0,1,1,0,0,0,0,1,1,0,0,0.806452,0.558442,0.230088,0.155303,0.375000,0.300000,1.0
31,1,0,0,0,0,0,1,0,0,0,0,1,0.306452,0.025974,0.464602,0.056818,0.531250,0.600000,0.0
32,1,0,1,1,0,0,0,0,0,0,0,1,0.887097,0.090909,0.332491,0.174242,0.539402,0.610303,1.0
33,1,0,1,1,0,1,1,0,1,0,0,0,0.870968,0.064935,0.199115,0.022727,0.625000,0.610303,1.0
34,0,0,1,1,1,0,0,0,1,0,1,1,0.403226,0.415584,0.818584,0.151515,0.406250,0.290000,1.0
35,1,1,0,0,0,0,0,0,0,0,0,1,0.645161,0.140000,0.332491,0.174242,0.539402,0.610303,1.0
36,1,0,1,1,1,0,0,0,0,0,0,0,1.016129,0.181818,0.349558,1.946970,0.218750,0.350000,1.0
37,1,0,1,1,1,0,0,0,0,1,0,1,0.500000,0.220779,0.185841,0.284091,0.250000,0.460000,1.0
38,0,0,1,1,0,0,1,0,0,0,0,1,0.338710,0.194805,0.712389,1.537879,0.375000,0.460000,0.0
39,1,0,1,1,1,0,0,0,1,1,0,0,0.209677,0.090909,0.575221,0.393939,0.250000,0.230000,1.0
40,1,0,1,0,0,0,0,0,0,0,0,1,0.435484,0.140000,0.332491,0.312427,0.539402,0.610303,1.0
41,1,1,1,1,0,0,1,0,0,0,0,1,0.516129,0.259740,1.106195,0.318182,0.531250,0.400000,1.0
42,0,0,0,0,0,0,0,0,0,0,0,1,0.483871,0.051948,-0.017699,0.166667,0.750000,1.000000,1.0
43,1,0,1,1,0,0,0,0,0,1,0,0,0.758065,0.116883,0.243363,0.295455,0.312500,0.660000,1.0
44,0,0,0,0,0,0,0,0,0,0,0,1,0.467742,0.051948,0.141593,0.795455,0.656250,1.000000,1.0
45,1,0,1,1,1,0,0,0,0,0,0,0,0.612903,0.259740,0.332491,2.401515,0.539402,0.610303,1.0
46,0,0,1,1,1,1,1,1,1,0,0,1,0.322581,0.116883,0.455752,0.318182,0.625000,0.390000,1.0
47,0,0,1,0,0,0,1,1,1,0,1,0,0.548387,0.506494,0.154867,0.401515,0.406250,0.610303,1.0
48,0,0,0,0,0,0,0,0,0,0,0,0,0.290323,0.038961,0.332491,0.075758,1.343750,0.610303,1.0
49,0,0,1,0,0,0,0,0,0,0,0,1,0.451613,0.077922,0.123894,0.295455,0.687500,0.730000,1.0
50,0,0,0,0,0,0,0,0,0,0,0,0,0.419355,0.090909,0.332491,0.174242,0.593750,0.610303,1.0
51,1,0,1,0,0,0,0,0,0,0,0,0,0.387097,0.116883,0.199115,0.602273,0.656250,0.540000,1.0
52,1,1,0,0,0,1,1,0,0,0,0,1,0.500000,0.051948,0.176991,0.053030,0.656250,0.620000,1.0

In [683]:
test.to_csv('../data/data_cleaned_test.csv', index_label=False)
train.to_csv('../data/cleaned_train.csv', index_label=False)
train

,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,HISTOLOGY,AGE,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,Class,OneHotSex
0,1,0,1,1,0,0,1,0,1,1,1,0,0.661290,0.584416,0.411504,0.541667,0.18750,0.31,DIE,1.0
1,0,0,1,0,0,0,1,1,1,0,1,0,0.709677,0.090909,0.333702,0.022727,0.28125,0.63,LIVE,1.0
2,1,0,1,0,0,0,1,0,0,0,0,1,0.532258,0.038961,0.141593,0.575758,0.59375,0.63,LIVE,1.0
3,0,0,1,0,0,1,1,1,1,1,1,0,0.290323,0.129870,0.668142,0.632576,0.75000,0.57,LIVE,1.0
4,1,0,1,0,0,1,1,0,1,0,0,1,0.435484,0.090909,0.185841,0.121212,0.71875,0.57,LIVE,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,0,0,1,1,1,0,0,1,0,0,0,1,0.258065,0.129870,0.725664,0.515152,0.62500,0.90,LIVE,1.0
98,1,0,0,0,0,0,1,0,0,0,0,0,0.500000,0.012987,0.942478,0.132576,0.53125,0.90,DIE,1.0
99,1,0,0,0,0,0,0,1,0,0,0,1,0.467742,0.064935,0.243363,0.113636,0.65625,0.85,LIVE,1.0
100,1,1,1,1,0,0,0,0,0,0,0,1,0.403226,0.090909,0.110619,0.117424,0.62500,0.56,LIVE,1.0
101,1,1,0,0,0,1,1,0,0,0,0,0,0.758065,0.090909,0.553097,0.799242,0.46875,0.67,LIVE,1.0